version: '3.8'

services:
  # 🍃 Base de datos MongoDB
  mongodb:
    image: mongo:7.0
    container_name: vel_arte_mongodb
    restart: unless-stopped
    ports:
      - "${MONGODB_EXTERNAL_PORT:-27018}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: vel_arte
    volumes:
      - mongodb_data:/data/db
    networks:
      - vel_arte_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 🔐 Servicio de Autenticación
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: vel_arte_auth
    restart: unless-stopped
    ports:
      - "${AUTH_SERVICE_EXTERNAL_PORT:-8001}:8000"
    environment:
      - MONGODB_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${DATABASE_NAME}?authSource=admin
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_NAME=${DATABASE_NAME}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - vel_arte_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 📦 Servicio de Productos
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: vel_arte_products
    restart: unless-stopped
    ports:
      - "${PRODUCT_SERVICE_EXTERNAL_PORT:-8002}:8001"
    environment:
      - MONGODB_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/vel_arte_products?authSource=admin
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - DATABASE_NAME=vel_arte_products
    env_file:
      - .env
    depends_on:
      auth-service:
        condition: service_healthy
    networks:
      - vel_arte_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:

networks:
  vel_arte_network:
    driver: bridge
